/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.malintha_agency.views;

import com.malintha_agency.controller.ReportController;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Dell
 */
public class DiscountReport extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private double totalDiscount = 0;
    private JasperReport jasperReport;
    private JasperPrint filledReport;
    private JRViewer jRViewer;
    private String t;
    private String f;

    /**
     * Creates new form ProfitAndLostReport
     */
    public DiscountReport() {
        initComponents();
        dtm = (DefaultTableModel) tbl_dr_disc.getModel();
        loadJasper();
    }

    private void loadJasper() {
        try {
            jasperReport = (JasperReport) JRLoader.loadObject(OrderDetailManager.class.getResourceAsStream("/com/malintha_agency/jasper/DiscountReport.jasper"));
        } catch (JRException ex) {
            Logger.getLogger(OrderDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dr_disc = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lbl_dr_taod = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_rm_viewreport1 = new javax.swing.JLabel();
        lbl_rm_viewreport2 = new javax.swing.JLabel();

        tbl_dr_disc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shop", "Issue Date", "Total Discount", "Total Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_dr_disc);
        if (tbl_dr_disc.getColumnModel().getColumnCount() > 0) {
            tbl_dr_disc.getColumnModel().getColumn(0).setResizable(false);
            tbl_dr_disc.getColumnModel().getColumn(1).setResizable(false);
            tbl_dr_disc.getColumnModel().getColumn(2).setResizable(false);
            tbl_dr_disc.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Total Amount of Discounts");

        lbl_dr_taod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_dr_taod.setForeground(new java.awt.Color(102, 102, 102));
        lbl_dr_taod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_dr_taod.setText("0.00");

        jPanel2.setOpaque(false);

        lbl_rm_viewreport1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_rm_viewreport1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_rm_viewreport1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rm_viewreport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malintha_agency/images/view.png"))); // NOI18N
        lbl_rm_viewreport1.setText(" View Report");
        lbl_rm_viewreport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rm_viewreport1MouseClicked(evt);
            }
        });

        lbl_rm_viewreport2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_rm_viewreport2.setForeground(new java.awt.Color(102, 102, 102));
        lbl_rm_viewreport2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rm_viewreport2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malintha_agency/images/Print.png"))); // NOI18N
        lbl_rm_viewreport2.setText("Print");
        lbl_rm_viewreport2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rm_viewreport2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_rm_viewreport1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_rm_viewreport2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_rm_viewreport1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbl_rm_viewreport2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_dr_taod, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_dr_taod)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_rm_viewreport1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rm_viewreport1MouseClicked
        getDetailsToTable();
    }//GEN-LAST:event_lbl_rm_viewreport1MouseClicked

    private void lbl_rm_viewreport2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rm_viewreport2MouseClicked
        try {
            HashMap<String, Object> data = new HashMap<>();
            data.put("Total Amount of Discounts", lbl_dr_taod.getText());
            data.put("From Date", f);
            data.put("To Date", t);
            filledReport = JasperFillManager.fillReport(jasperReport, data, new JRTableModelDataSource(dtm));
            jRViewer = new JRViewer(filledReport);
            jRViewer.setOpaque(true);
            jRViewer.setBackground(Color.WHITE);
            new JasperViewer(jRViewer);
            //PrintJasper.PrintReportToPrinter(filledReport);
        } catch (JRException ex) {
            Logger.getLogger(OrderDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbl_rm_viewreport2MouseClicked

    private void getDetailsToTable() {

        f = Report_Manager.firstdate;
        t = Report_Manager.seconddate;
        totalDiscount = 0;
        String companyname = Report_Manager.companyname;
        if (f != null && t != null && companyname != null) {
            if (!f.equals("") && !t.equals("") && !companyname.equals("")) {
                try {
                    com.malintha_agency.model.CreditReport[] creditreports = ReportController.getCreditReport(companyname, f, t);
                    dtm.setRowCount(0);
                    lbl_dr_taod.setText("0.00");
                    if (creditreports != null) {
                        for (com.malintha_agency.model.CreditReport c : creditreports) {
                            if (c != null) {
                                Object[] row = {c.getShopname(), c.getIssuedate(), c.getDiscount() + "", c.getTotalpayment() + ""};
                                totalDiscount += c.getDiscount();
                                dtm.addRow(row);
                            }
                        }
                        lbl_dr_taod.setText(Double.toString(totalDiscount));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SupplierReport.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SupplierReport.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_dr_taod;
    private javax.swing.JLabel lbl_rm_viewreport1;
    private javax.swing.JLabel lbl_rm_viewreport2;
    private javax.swing.JTable tbl_dr_disc;
    // End of variables declaration//GEN-END:variables
}
