/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.malintha_agency.views;

import com.malintha_agency.controller.RouteController;
import com.malintha_agency.model.Route;
import com.malintha_agency.view.validation.Validation;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZeeLot
 */
public class Order_Shop_New_Route extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private int id = -1;

    /**
     * Creates new form Stock_Product_New_Product
     */
    public Order_Shop_New_Route() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Malintha Distributors");
        icon();
        dtm = (DefaultTableModel) tbl_osnr_route.getModel();
        tbl_osnr_route.removeColumn(tbl_osnr_route.getColumnModel().getColumn(2));
        loadAllRoutes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_osnr_route = new javax.swing.JTable();
        btn_osnr_add = new javax.swing.JButton();
        btn_osnr_remove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_osnr_rno = new javax.swing.JTextField();
        txt_osnr_rn = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_osnr_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tbl_osnr_route.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Route No", "Route Name", "RID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_osnr_route.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_osnr_routeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_osnr_route);
        if (tbl_osnr_route.getColumnModel().getColumnCount() > 0) {
            tbl_osnr_route.getColumnModel().getColumn(0).setResizable(false);
            tbl_osnr_route.getColumnModel().getColumn(1).setResizable(false);
            tbl_osnr_route.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_osnr_add.setText("Add");
        btn_osnr_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osnr_addActionPerformed(evt);
            }
        });

        btn_osnr_remove.setText("Remove");
        btn_osnr_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osnr_removeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(78, 44, 211));
        jPanel2.setForeground(new java.awt.Color(78, 44, 211));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Add New Route");

        lblOrderId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Route No");

        txt_osnr_rno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_osnr_rnoKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Route Name");

        btn_osnr_clear.setText("Clear");
        btn_osnr_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osnr_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_osnr_add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_osnr_remove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_osnr_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_osnr_rno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(txt_osnr_rn, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_osnr_rno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_osnr_rn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_osnr_add)
                    .addComponent(btn_osnr_remove)
                    .addComponent(btn_osnr_clear))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_osnr_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osnr_addActionPerformed
        if (isNotBlank()) {
            save();
        }
    }//GEN-LAST:event_btn_osnr_addActionPerformed

    private void btn_osnr_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osnr_removeActionPerformed
        if (isNotBlank()) {
            remove();
        }
    }//GEN-LAST:event_btn_osnr_removeActionPerformed

    private void tbl_osnr_routeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_osnr_routeMouseClicked
        select();
    }//GEN-LAST:event_tbl_osnr_routeMouseClicked

    private void btn_osnr_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osnr_clearActionPerformed
        clear();
    }//GEN-LAST:event_btn_osnr_clearActionPerformed

    private void txt_osnr_rnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_osnr_rnoKeyReleased
        Validation.numberOnly(txt_osnr_rn);
    }//GEN-LAST:event_txt_osnr_rnoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_Shop_New_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_Shop_New_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_Shop_New_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_Shop_New_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_Shop_New_Route().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_osnr_add;
    private javax.swing.JButton btn_osnr_clear;
    private javax.swing.JButton btn_osnr_remove;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JTable tbl_osnr_route;
    private javax.swing.JTextField txt_osnr_rn;
    private javax.swing.JTextField txt_osnr_rno;
    // End of variables declaration//GEN-END:variables

    private void save() {

        int routeno = Integer.parseInt(txt_osnr_rno.getText());
        String name = txt_osnr_rn.getText();

        if (!name.equals("")) {
            try {

                if (id == -1) {

                    Route r = new Route();
                    r.setRouteno(routeno);
                    r.setRoutename(name);
                    r.setExtrainfo("");
                    String msg = new RouteController().saveRoute(r);

                    if (msg.equals("ok")) {
                        clear();
                        loadAllRoutes();
                        JOptionPane.showMessageDialog(this, "Information saved", "Successfull", JOptionPane.INFORMATION_MESSAGE);
                    } else if (msg.equals("ae")) {
                        JOptionPane.showMessageDialog(this, "Route Already exist", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Database Failed", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    Route r = new Route();
                    r.setRouteid(id);
                    r.setRouteno(routeno);
                    r.setRoutename(name);
                    String msg = new RouteController().modifyRoute(r);

                    if (msg.equals("ok")) {
                        clear();

                        loadAllRoutes();
                        JOptionPane.showMessageDialog(this, "Information saved", "Successfull", JOptionPane.INFORMATION_MESSAGE);
                    } else if (msg.equals("ude")) {
                        JOptionPane.showMessageDialog(this, "Route doesnt exist", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Database Failed", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                }
            } catch (SQLException ex1) {
                Logger.getLogger(Order_Shop_New_Route.class.getName()).log(Level.SEVERE, null, ex1);
            } catch (ClassNotFoundException ex1) {
                Logger.getLogger(Order_Shop_New_Route.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }

    }

    private void clear() {
        id = -1;
        txt_osnr_rn.setText("");
        txt_osnr_rno.setText("");

    }

    private void select() {
        int row = tbl_osnr_route.getSelectedRow();
        if (row != -1) {

            txt_osnr_rno.setText(dtm.getValueAt(row, 0).toString());
            txt_osnr_rn.setText(dtm.getValueAt(row, 1).toString());

            id = (int) dtm.getValueAt(row, 2);
            System.out.println(id);
        }

    }

    private void loadAllRoutes() {
        try {
            Route[] routes = new RouteController().viewAllRoutes();
            if (routes != null) {
                dtm.setRowCount(0);
                for (Route r : routes) {
                    if (r != null) {
                        Object[] row = {r.getRouteno(), r.getRoutename(), r.getRouteid()};
                        dtm.addRow(row);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void remove() {
        // if (id != -1) {
        try {
            String msg = new RouteController().removeRoute(id);
            if (msg.equals("ok")) {

                clear();
                loadAllRoutes();
                JOptionPane.showMessageDialog(this, "Information removed", "Successfull", JOptionPane.INFORMATION_MESSAGE);

            } else if (msg.equals("ae")) {
                id = -1;
                JOptionPane.showMessageDialog(this, "Route doesn't exist", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                id = -1;
                JOptionPane.showMessageDialog(this, "Database Failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        //}

    }

    private boolean isNotBlank() {
        return (!txt_osnr_rn.getText().equals("") && !txt_osnr_rno.getText().equals(""));
    }
    
    private void icon(){
        URL iconURL=this.getClass().getResource("/com/malintha_agency/images/logo logo.jpg");
        ImageIcon imageIcon=new ImageIcon(iconURL);
        setIconImage(imageIcon.getImage());
    }
}
