/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.malintha_agency.views;

import com.malintha_agency.controller.RouteController;
import com.malintha_agency.controller.ShopController;
import com.malintha_agency.model.Route;
import com.malintha_agency.model.Shop;
import com.malintha_agency.view.validation.Validation;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ZeeLot
 */
public class Order_Shop_Manager extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private int id = -1;

    /**
     * Creates new form Stock_InvoiceProduct_Manager
     */
    public Order_Shop_Manager() {
        initComponents();
        dtm = (DefaultTableModel) tbl_osm_sinfo.getModel();
        tbl_osm_sinfo.removeColumn(tbl_osm_sinfo.getColumnModel().getColumn(5));
        loadAllShops();
        loadallroutestoCombo();
        AutoCompleteDecorator.decorate(cmb_osm_route);
        AutoCompleteDecorator.decorate(cmb_osm_rs);
//        cmb_osm_route.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_osm_rs = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_osm_sinfo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmb_osm_route = new javax.swing.JComboBox<>();
        txt_osm_sn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_osm_ow = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txt_osm_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_osm_contact = new javax.swing.JTextField();
        btn_osm_remove = new javax.swing.JButton();
        btn_osm_edit = new javax.swing.JButton();
        btn_osm_save = new javax.swing.JButton();
        btn_osm_clear = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(78, 44, 211));
        jPanel2.setPreferredSize(new java.awt.Dimension(802, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Find By");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Route");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malintha_agency/images/search 30x30.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malintha_agency/images/Route.png"))); // NOI18N
        jLabel4.setText("  New Route");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        cmb_osm_rs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_osm_rsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_osm_rs, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_osm_rs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);

        tbl_osm_sinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Route", "Shop Name", "Owner", "E mail", "Contact", "SID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_osm_sinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_osm_sinfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_osm_sinfo);
        if (tbl_osm_sinfo.getColumnModel().getColumnCount() > 0) {
            tbl_osm_sinfo.getColumnModel().getColumn(0).setResizable(false);
            tbl_osm_sinfo.getColumnModel().getColumn(1).setResizable(false);
            tbl_osm_sinfo.getColumnModel().getColumn(2).setResizable(false);
            tbl_osm_sinfo.getColumnModel().getColumn(3).setResizable(false);
            tbl_osm_sinfo.getColumnModel().getColumn(4).setResizable(false);
            tbl_osm_sinfo.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Route");

        txt_osm_sn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Shop Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Owner");

        txt_osm_ow.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(txt_osm_ow, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_osm_sn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_osm_route, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_osm_route, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_osm_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_osm_ow, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txt_osm_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_osm_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_osm_emailKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Email");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Contact");

        txt_osm_contact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_osm_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_osm_contactKeyReleased(evt);
            }
        });

        btn_osm_remove.setText("Remove");
        btn_osm_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osm_removeActionPerformed(evt);
            }
        });

        btn_osm_edit.setText("Edit");
        btn_osm_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osm_editActionPerformed(evt);
            }
        });

        btn_osm_save.setText("Save");
        btn_osm_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osm_saveActionPerformed(evt);
            }
        });

        btn_osm_clear.setText("Clear");
        btn_osm_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osm_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(btn_osm_remove))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_osm_email, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_osm_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_osm_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_osm_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_osm_save, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_osm_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_osm_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_osm_remove)
                    .addComponent(btn_osm_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_osm_save)
                    .addComponent(btn_osm_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Order_Shop_New_Route new_Route = new Order_Shop_New_Route();
        new_Route.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txt_osm_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_osm_emailKeyReleased
        Validation.emailValidate(txt_osm_email);
    }//GEN-LAST:event_txt_osm_emailKeyReleased

    private void txt_osm_contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_osm_contactKeyReleased
        Validation.validatePhoneNumber(txt_osm_contact);
    }//GEN-LAST:event_txt_osm_contactKeyReleased

    private void tbl_osm_sinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_osm_sinfoMouseClicked
        select();
    }//GEN-LAST:event_tbl_osm_sinfoMouseClicked

    private void btn_osm_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osm_saveActionPerformed
        if (isNotBlank()) {
            save();
        }
    }//GEN-LAST:event_btn_osm_saveActionPerformed

    private void btn_osm_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osm_editActionPerformed
        if (isNotBlank()) {
            edit();
        }
    }//GEN-LAST:event_btn_osm_editActionPerformed

    private void btn_osm_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osm_removeActionPerformed
        if (isNotBlank()) {
            remove();
        }
    }//GEN-LAST:event_btn_osm_removeActionPerformed

    private void btn_osm_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osm_clearActionPerformed
        clear();
    }//GEN-LAST:event_btn_osm_clearActionPerformed

    private void cmb_osm_rsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_osm_rsItemStateChanged
        findbyRouteNo();
    }//GEN-LAST:event_cmb_osm_rsItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_osm_clear;
    private javax.swing.JButton btn_osm_edit;
    private javax.swing.JButton btn_osm_remove;
    private javax.swing.JButton btn_osm_save;
    private javax.swing.JComboBox<String> cmb_osm_route;
    private javax.swing.JComboBox<String> cmb_osm_rs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_osm_sinfo;
    private javax.swing.JTextField txt_osm_contact;
    private javax.swing.JTextField txt_osm_email;
    private javax.swing.JTextField txt_osm_ow;
    private javax.swing.JTextField txt_osm_sn;
    // End of variables declaration//GEN-END:variables

    private void save() {
        id = -1;
        Route r = null;
        try {
            int route = 0;
            if (cmb_osm_route.getItemCount() > 0) {
                route = Integer.parseInt(cmb_osm_route.getSelectedItem().toString());

                r = new RouteController().findRoute(route);
            }
            String shopname = txt_osm_sn.getText();
            String owner = txt_osm_ow.getText();
            String email = txt_osm_email.getText();
            String contact = txt_osm_contact.getText();

            Shop shop = new Shop();
            shop.setRouteno(r.getRouteid());
            shop.setShopname(shopname);
            shop.setShopemail(email);
            shop.setShopowner(owner);
            shop.setContactno(contact);

            String msg = new ShopController().saveShop(shop);
            if (msg.equals("ok")) {
                clear();
                loadAllShops();
                JOptionPane.showMessageDialog(this, "Information saved", "Successfull", JOptionPane.INFORMATION_MESSAGE);
            } else if (msg.equals("ae")) {
                JOptionPane.showMessageDialog(this, "Shop Already exist", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Database Failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadAllShops() {
        try {
            Shop[] shops = new ShopController().viewShops();
            if (shops != null) {
                dtm.setRowCount(0);
                for (Shop s : shops) {
                    if (s != null) {
                        Object[] row = {s.getRouteno(), s.getShopname(), s.getShopowner(), s.getShopemail(), s.getContactno(), s.getShopid()};
                        dtm.addRow(row);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void select() {
        int row = tbl_osm_sinfo.getSelectedRow();
        if (row != -1) {
            if (cmb_osm_route.getItemCount() > 0) {
                cmb_osm_route.setSelectedItem(dtm.getValueAt(row, 0));
            }
            if (dtm.getValueAt(row, 0).toString().equals("")) {
                cmb_osm_route.setSelectedIndex(0);
            }
            txt_osm_sn.setText(dtm.getValueAt(row, 1).toString());
            txt_osm_ow.setText(dtm.getValueAt(row, 2).toString());
            txt_osm_email.setText(dtm.getValueAt(row, 3).toString());
            txt_osm_contact.setText(dtm.getValueAt(row, 4).toString());
            id = (int) dtm.getValueAt(row, 5);
        }

    }

    private void edit() {
        int route = 0;
        if (cmb_osm_route.getItemCount() > 0) {
            route = Integer.parseInt(cmb_osm_route.getSelectedItem().toString());
        }
        if (id != -1) {
            try {
                String shopname = txt_osm_sn.getText();
                String owner = txt_osm_ow.getText();
                String email = txt_osm_email.getText();
                String contact = txt_osm_contact.getText();

                Shop shop = new Shop();
                shop.setShopid(id);
                shop.setRouteno(route);
                shop.setShopname(shopname);
                shop.setShopemail(email);
                shop.setShopowner(owner);
                shop.setContactno(contact);

                String msg = new ShopController().modifyShop(shop);
                if (msg.equals("ok")) {
                    id = -1;
                    clear();
                    loadAllShops();
                    JOptionPane.showMessageDialog(this, "Information updated", "Successfull", JOptionPane.INFORMATION_MESSAGE);
                    id = -1;
                } else if (msg.equals("ae")) {
                    id = -1;
                    JOptionPane.showMessageDialog(this, "Shop doesn't exist", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    id = -1;
                    JOptionPane.showMessageDialog(this, "Database Failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void remove() {
        if (id != -1) {
            try {
                String msg = new ShopController().removeShop(id);
                if (msg.equals("ok")) {
                    id = -1;
                    clear();
                    loadAllShops();
                    JOptionPane.showMessageDialog(this, "Information removed", "Successfull", JOptionPane.INFORMATION_MESSAGE);
                    id = -1;
                } else if (msg.equals("ae")) {
                    id = -1;
                    JOptionPane.showMessageDialog(this, "Shop doesn't exist", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    id = -1;
                    JOptionPane.showMessageDialog(this, "Database Failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void loadallroutestoCombo() {

        Route[] route;
        try {
            route = new RouteController().viewAllRoutes();
            if (route != null) {
                cmb_osm_route.removeAllItems();
                for (Route r : route) {

                    cmb_osm_route.addItem(Integer.toString(r.getRouteno()));
                    cmb_osm_rs.addItem(Integer.toString(r.getRouteno()));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void clear() {
        id = -1;
        cmb_osm_route.setSelectedIndex(0);
        txt_osm_sn.setText("");
        txt_osm_contact.setText("");
        txt_osm_email.setText("");
        txt_osm_ow.setText("");
        loadAllShops();
    }

    private void findbyRouteNo() {
        
        if (cmb_osm_rs.getItemCount() > 0 && !cmb_osm_rs.getSelectedItem().toString().equals("")) {
            Route r=null;
            try {
                int routeno = Integer.parseInt(cmb_osm_rs.getSelectedItem().toString());
                r = new RouteController().findRoute(routeno);
                Shop[] shops = new ShopController().findShopByRoute(r.getRouteid());
                if (shops != null) {
                    dtm.setRowCount(0);
                    for (Shop s : shops) {
                        if (s != null) {
                            Object[] row = {s.getRouteno(), s.getShopname(), s.getShopowner(), s.getShopemail(), s.getContactno(), s.getShopid()};
                            dtm.addRow(row);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Order_Shop_Manager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private boolean isNotBlank() {
        return (!txt_osm_contact.getText().equals("") && !txt_osm_email.getText().equals("") && !txt_osm_ow.getText().equals("") && !txt_osm_sn.getText().equals("") && !cmb_osm_route.getSelectedItem().equals("") && !cmb_osm_rs.getSelectedItem().equals(""));
    }
}
