/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.malintha_agency.views;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JPanel;
import com.malintha_agency.model.Supplier;
import com.malintha_agency.controller.SupplierController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ZeeLot
 */
public class Report_Manager extends javax.swing.JPanel {

    private DateFormat df;

    public static String firstdate;
    public static String seconddate;
    public static String companyname;

    public static int selected = 0;

    /**
     * Creates new form Stock_InvoiceProduct_Manager
     */
    public Report_Manager() {
        initComponents();
        jdc_rm_fd.setDate(new Date());
        jdc_rm_sd.setDate(new Date());
        df = new SimpleDateFormat("yyyy-MM-dd");
        firstdate = new SimpleDateFormat("yyyy-MM-dd").format(jdc_rm_fd.getDate());
        seconddate = new SimpleDateFormat("yyyy-MM-dd").format(jdc_rm_sd.getDate());
        LoadAllSupplierCombo();
        AutoCompleteDecorator.decorate(cmb_rm_companyname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_rm_pl = new javax.swing.JLabel();
        lbl_rm_sup = new javax.swing.JLabel();
        lbl_rm_sale = new javax.swing.JLabel();
        lbl_rm_damage = new javax.swing.JLabel();
        lbl_rm_discount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jdc_rm_fd = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jdc_rm_sd = new com.toedter.calendar.JDateChooser();
        cmb_rm_companyname = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(78, 44, 211));
        jPanel2.setPreferredSize(new java.awt.Dimension(802, 100));

        lbl_rm_pl.setBackground(new java.awt.Color(78, 44, 211));
        lbl_rm_pl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_rm_pl.setForeground(new java.awt.Color(204, 204, 204));
        lbl_rm_pl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rm_pl.setText("Profit & Lost");
        lbl_rm_pl.setOpaque(true);
        lbl_rm_pl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rm_plMouseClicked(evt);
            }
        });

        lbl_rm_sup.setBackground(new java.awt.Color(78, 44, 211));
        lbl_rm_sup.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_rm_sup.setForeground(new java.awt.Color(204, 204, 204));
        lbl_rm_sup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rm_sup.setText("Supplier");
        lbl_rm_sup.setOpaque(true);
        lbl_rm_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rm_supMouseClicked(evt);
            }
        });

        lbl_rm_sale.setBackground(new java.awt.Color(78, 44, 211));
        lbl_rm_sale.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_rm_sale.setForeground(new java.awt.Color(204, 204, 204));
        lbl_rm_sale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rm_sale.setText("Sales");
        lbl_rm_sale.setOpaque(true);
        lbl_rm_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rm_saleMouseClicked(evt);
            }
        });

        lbl_rm_damage.setBackground(new java.awt.Color(78, 44, 211));
        lbl_rm_damage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_rm_damage.setForeground(new java.awt.Color(204, 204, 204));
        lbl_rm_damage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rm_damage.setText("Damages");
        lbl_rm_damage.setOpaque(true);
        lbl_rm_damage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rm_damageMouseClicked(evt);
            }
        });

        lbl_rm_discount.setBackground(new java.awt.Color(78, 44, 211));
        lbl_rm_discount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_rm_discount.setForeground(new java.awt.Color(204, 204, 204));
        lbl_rm_discount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rm_discount.setText("Discounts");
        lbl_rm_discount.setOpaque(true);
        lbl_rm_discount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rm_discountMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setText("From");

        jdc_rm_fd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdc_rm_fdMouseClicked(evt);
            }
        });
        jdc_rm_fd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdc_rm_fdPropertyChange(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("To");

        jdc_rm_sd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdc_rm_sdMouseClicked(evt);
            }
        });
        jdc_rm_sd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdc_rm_sdPropertyChange(evt);
            }
        });

        cmb_rm_companyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rm_companynameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Company");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_rm_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbl_rm_sup, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lbl_rm_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lbl_rm_damage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(lbl_rm_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jdc_rm_fd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdc_rm_sd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_rm_companyname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rm_discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_rm_damage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rm_sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_rm_sup)
                    .addComponent(lbl_rm_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmb_rm_companyname, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jdc_rm_sd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdc_rm_fd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    void setColorToPanels(JLabel panel) {
        panel.setBackground(new Color(135, 112, 225));
    }

    void resetColorToPanels(JLabel panel) {
        panel.setBackground(new Color(76, 41, 211));
    }

    private void lbl_rm_plMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rm_plMouseClicked
        jLabel7.setText("  Profit & Lost");
        resetAllLabels();
        setColorToPanels(lbl_rm_pl);

        setOption(1);

        ProfitAndLostReport report = new ProfitAndLostReport();
        jPanel3.removeAll();
        report.setSize(jPanel3.getSize());
        jPanel3.add(report);
        jPanel3.repaint();
        jPanel3.validate();
    }//GEN-LAST:event_lbl_rm_plMouseClicked

    private void lbl_rm_supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rm_supMouseClicked
        jLabel7.setText("  Total Payments for Supplier");
        resetAllLabels();
        setColorToPanels(lbl_rm_sup);

        setOption(2);

        SupplierReport report = new SupplierReport();
        jPanel3.removeAll();
        report.setSize(jPanel3.getSize());
        jPanel3.add(report);
        jPanel3.repaint();
        jPanel3.validate();
    }//GEN-LAST:event_lbl_rm_supMouseClicked

    private void lbl_rm_damageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rm_damageMouseClicked
        jLabel7.setText("  Total Amount of Damages");
        resetAllLabels();
        setColorToPanels(lbl_rm_damage);

        setOption(3);

        DamageReport report = new DamageReport();
        jPanel3.removeAll();
        report.setSize(jPanel3.getSize());
        jPanel3.add(report);
        jPanel3.repaint();
        jPanel3.validate();
    }//GEN-LAST:event_lbl_rm_damageMouseClicked

    private void lbl_rm_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rm_saleMouseClicked
        jLabel7.setText("  Total Payments from Delivery");
        resetAllLabels();
        setColorToPanels(lbl_rm_sale);

        setOption(4);

        SalesReport report = new SalesReport();
        jPanel3.removeAll();
        report.setSize(jPanel3.getSize());
        jPanel3.add(report);
        jPanel3.repaint();
        jPanel3.validate();
    }//GEN-LAST:event_lbl_rm_saleMouseClicked

    private void jdc_rm_fdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdc_rm_fdMouseClicked
        firstdate = new SimpleDateFormat("yyyy-MM-dd").format(jdc_rm_fd.getDate());

    }//GEN-LAST:event_jdc_rm_fdMouseClicked

    private void jdc_rm_sdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdc_rm_sdMouseClicked
        seconddate = new SimpleDateFormat("yyyy-MM-dd").format(jdc_rm_sd.getDate());
    }//GEN-LAST:event_jdc_rm_sdMouseClicked

    private void jdc_rm_fdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdc_rm_fdPropertyChange
        firstdate = new SimpleDateFormat("yyyy-MM-dd").format(jdc_rm_fd.getDate());
    }//GEN-LAST:event_jdc_rm_fdPropertyChange

    private void jdc_rm_sdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdc_rm_sdPropertyChange
        seconddate = new SimpleDateFormat("yyyy-MM-dd").format(jdc_rm_sd.getDate());
    }//GEN-LAST:event_jdc_rm_sdPropertyChange

    private void cmb_rm_companynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rm_companynameActionPerformed
        companyname = cmb_rm_companyname.getSelectedItem().toString();
    }//GEN-LAST:event_cmb_rm_companynameActionPerformed

    private void lbl_rm_discountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rm_discountMouseClicked
        jLabel7.setText("  Total Amount of Discounts");
        resetAllLabels();
        setColorToPanels(lbl_rm_discount);

        setOption(4);

        DiscountReport report = new DiscountReport();
        jPanel3.removeAll();
        report.setSize(jPanel3.getSize());
        jPanel3.add(report);
        jPanel3.repaint();
        jPanel3.validate();
    }//GEN-LAST:event_lbl_rm_discountMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_rm_companyname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jdc_rm_fd;
    private com.toedter.calendar.JDateChooser jdc_rm_sd;
    private javax.swing.JLabel lbl_rm_damage;
    private javax.swing.JLabel lbl_rm_discount;
    private javax.swing.JLabel lbl_rm_pl;
    private javax.swing.JLabel lbl_rm_sale;
    private javax.swing.JLabel lbl_rm_sup;
    // End of variables declaration//GEN-END:variables

    private void resetAllLabels() {
        resetColorToPanels(lbl_rm_pl);
        resetColorToPanels(lbl_rm_sup);
        resetColorToPanels(lbl_rm_sale);
        resetColorToPanels(lbl_rm_damage);
        resetColorToPanels(lbl_rm_discount);
    }

    private void setOption(int i) {
        selected = i;
    }

    private void LoadAllSupplierCombo() {
        try {
            Supplier[] suppliers = new SupplierController().viewSuppliers();
            if (suppliers != null) {
                cmb_rm_companyname.removeAllItems();
                for (Supplier s : suppliers) {
                    if (s != null) {
                        cmb_rm_companyname.addItem(s.getSuppliername());
                    }
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Report_Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Report_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
